usingSystem;
usingSystem.Collections.Generic;
usingSystem.IO;
usingProtoCore.BuildData;
usingProtoCore.DSASM;
usingProtoCore.Properties;

namespaceProtoCore
{
publicclassBuildHaltException:Exception
{
publicstringErrorMessage
{
get;privateset;
}

publicBuildHaltException(stringmessage)
{
ErrorMessage=message+'\n';
}
}

namespaceBuildData
{
publicenumErrorType
{
SyntaxError,
SemanticError,
MaxErrorID
}

publicenumWarningID
{
AccessViolation,
CallingConstructorInConstructor,
CallingConstructorOnInstance,
CallingNonStaticMethodOnClass,
FunctionAbnormalExit,
FunctionAlreadyDefined,
FunctionNotFound,
IdUnboundIdentifier,
InvalidStaticCyclicDependency,
InvalidRangeExpression,
InvalidThis,
MissingReturnStatement,
Parsing,
TypeUndefined,
PropertyNotFound,
FileNotFound,
MultipleSymbolFound,
MultipleSymbolFoundFromName,
}

publicstructErrorEntry
{
publicErrorTypeID;
publicstringFileName;
publicstringMessage;
publicintLine;
publicintColumn;
}

publicstructWarningEntry
{
publicWarningIDID;
publicstringMessage;
publicintLine;
publicintColumn;
publicGuidGraphNodeGuid;
publicintAstID;
publicstringFileName;
publicSymbolNodeUnboundVariableSymbolNode;
}
}

///<summary>
///VMprintoutmessage
///</summary>
publicclassOutputMessage
{
publicenumMessageType{Info,Warning,Error}
//Aconstructorformessageonlyforprint-outpurpose
publicOutputMessage(stringmessage)
{
Type=MessageType.Info;
Message=message;
FilePath=string.Empty;
Line=-1;
Column=-1;
}

//Aconstructorforsourcelocationrelatedmessages.
publicOutputMessage(MessageTypetype,stringmessage,
stringfilePath,intline,intcolumn)
{
Type=type;
Message=message;
FilePath=filePath;
Line=line;
Column=column;
}

//Aconstructorforinfomessageswithoutlineandcolume.
internalOutputMessage(MessageTypetype,stringmessage,stringfilePath)
{
Type=type;
Message=message;
FilePath=filePath;
Line=-1;
Column=-1;
}

publicMessageTypeType{get;privateset;}
publicstringFilePath{get;privateset;}
publicintLine{get;privateset;}
publicintColumn{get;privateset;}
publicstringMessage{get;privateset;}
publicboolContinue{get;set;}
}

publicinterfaceIOutputStream
{
voidWrite(OutputMessagemessage);
}

publicclassTextOutputStream:IOutputStream
{
publicStringWriterTextStream{get;privateset;}
publicDictionary<int,List<string>>Map{get;privateset;}

publicTextOutputStream(Dictionary<int,List<string>>map)
{
TextStream=newStringWriter();
Map=map;
}

publicvoidWrite(ProtoCore.OutputMessagemessage)
{
if(null==message)
return;

if(string.IsNullOrEmpty(message.FilePath))
{
//Type:Message
stringformatWithoutFile="{0}:{1}";
TextStream.WriteLine(string.Format(formatWithoutFile,
message.Type.ToString(),message.Message));
}
else
{
//Type:Message(File-Line,Column)
stringformatWithFile="{0}:{1}({2}-line:{3},col:{4})";
TextStream.WriteLine(string.Format(formatWithFile,
message.Type.ToString(),message.Message,
message.FilePath,message.Line,message.Column));
}

if(message.Type==ProtoCore.OutputMessage.MessageType.Warning)
message.Continue=true;
}
}

publicclassConsoleOutputStream:IOutputStream
{
publicConsoleOutputStream()
{
}

publicvoidWrite(ProtoCore.OutputMessagemessage)
{
if(null==message)
return;

#ifDEBUG
if(string.IsNullOrEmpty(message.FilePath))
{
//Type:Message
stringformatWithoutFile="{0}:{1}";
System.Console.WriteLine(string.Format(formatWithoutFile,
message.Type.ToString(),message.Message));
}
else
{
//Type:Message(File-Line,Column)
stringformatWithFile="{0}:{1}({2}-line:{3},col:{4})";
System.Console.WriteLine(string.Format(formatWithFile,
message.Type.ToString(),message.Message,
message.FilePath,message.Line,message.Column));
}
#endif

if(message.Type==ProtoCore.OutputMessage.MessageType.Warning)
message.Continue=true;
}
}

publicclassBuildStatus
{
privateProtoCore.Corecore;
privateSystem.IO.TextWriterconsoleOut=System.Console.Out;
privatereadonlyboolLogWarnings=true;
privatereadonlyboollogErrors=true;
privatereadonlybooldisplayBuildResult=true;

publicIOutputStreamMessageHandler{get;set;}

privateList<BuildData.WarningEntry>warnings;
publicIEnumerable<BuildData.WarningEntry>Warnings
{
get
{
returnwarnings;
}
}

publicintWarningCount
{
get{returnwarnings.Count;}
}

privatereadonlyList<BuildData.ErrorEntry>errors;
publicIEnumerable<BuildData.ErrorEntry>Errors
{
get
{
returnerrors;
}
}

publicintErrorCount
{
get{returnerrors.Count;}
}

publicboolBuildSucceeded
{
get
{
returnErrorCount==0;
}
}

//logsallerrorsandwarningsbydefault
//
publicBuildStatus(Corecore,System.IO.TextWriterwriter=null,boolerrorAsWarning=false)
{
this.core=core;
warnings=newList<BuildData.WarningEntry>();
errors=newList<BuildData.ErrorEntry>();

if(writer!=null)
{
consoleOut=System.Console.Out;
System.Console.SetOut(writer);
}

//Createadefaultconsoleoutputstream,andthiscan
//beoverwritteninIDEbyassigningitadifferentvalue.
this.MessageHandler=newConsoleOutputStream();
displayBuildResult=logErrors=LogWarnings=core.Options.Verbose;
}

///<summary>
///RemoveunboundvariablewarningsthatmatchallsymbolsinthesymbolList
///</summary>
///<paramname="symbolList"></param>
publicvoidRemoveUnboundVariableWarnings(HashSet<SymbolNode>symbolList)
{
foreach(SymbolNodesymbolinsymbolList)
{
//Removeallwarningsthatmatchthesymbol
warnings.RemoveAll(w=>w.ID==BuildData.WarningID.IdUnboundIdentifier&&w.UnboundVariableSymbolNode!=null&&w.UnboundVariableSymbolNode.Equals(symbol));
}
}

publicvoidClearWarnings()
{
warnings.Clear();
}

publicvoidClearWarningsForAst(intastID)
{
warnings.RemoveAll(w=>w.AstID.Equals(astID));
}

publicvoidClearWarningsForGraph(Guidguid)
{
warnings.RemoveAll(w=>w.GraphNodeGuid.Equals(guid));
}

publicvoidClearErrors()
{
errors.Clear();
}

publicvoidLogSyntaxError(stringmsg,stringfileName=null,intline=-1,intcol=-1)
{
varlocalizedMessage=LocalizeErrorMessage(msg);

#ifDEBUG
if(logErrors)
{
varmessage=string.Format("{0}({1},{2})Error:{3}",fileName,line,col,localizedMessage);
System.Console.WriteLine(message);
}
#endif

varerrorEntry=newBuildData.ErrorEntry
{
ID=BuildData.ErrorType.SyntaxError,
FileName=fileName,
Message=localizedMessage,
Line=line,
Column=col
};

if(core.Options.IsDeltaExecution)
{
}

errors.Add(errorEntry);


OutputMessageoutputmessage=newOutputMessage(OutputMessage.MessageType.Error,localizedMessage.Trim(),fileName,line,col);


if(MessageHandler!=null)
{
MessageHandler.Write(outputmessage);
if(!outputmessage.Continue)
thrownewBuildHaltException(localizedMessage);
}
}

privatestringLocalizeErrorMessage(stringerrorMessage)
{
switch(errorMessage)
{
case"EOFexpected":
returnProperties.Resources.EOF_expected;
case"identexpected":
returnProperties.Resources.ident_expected;
case"numberexpected":
returnProperties.Resources.number_expected;
case"floatexpected":
returnProperties.Resources.float_expected;
case"textstringexpected":
returnProperties.Resources.textstring_expected;
case"charexpected":
returnProperties.Resources.char_expected;
case"periodexpected":
returnProperties.Resources.period_expected;
case"postfixed_replicationguideexpected":
returnProperties.Resources.postfixed_replicationguide_expected;
case"openbracketexpected":
returnProperties.Resources.openbracket_expected;
case"closebracketexpected":
returnProperties.Resources.closebracket_expected;
case"openparenexpected":
returnProperties.Resources.openparen_expected;
case"closeparenexpected":
returnProperties.Resources.closeparen_expected;
case"notexpected":
returnProperties.Resources.not_expected;
case"negexpected":
returnProperties.Resources.neg_expected;
case"pipeexpected":
returnProperties.Resources.pipe_expected;
case"lessthanexpected":
returnProperties.Resources.lessthan_expected;
case"greaterthanexpected":
returnProperties.Resources.greaterthan_expected;
case"lessequalexpected":
returnProperties.Resources.lessequal_expected;
case"greaterequalexpected":
returnProperties.Resources.greaterequal_expected;
case"equalexpected":
returnProperties.Resources.equal_expected;
case"notequalexpected":
returnProperties.Resources.notequal_expected;
case"endlineexpected":
returnProperties.Resources.endline_expected;
case"rangeopexpected":
returnProperties.Resources.rangeop_expected;
case"kw_nativeexpected":
returnProperties.Resources.kw_native_expected;
case"kw_classexpected":
returnProperties.Resources.kw_class_expected;
case"kw_constructorexpected":
returnProperties.Resources.kw_constructor_expected;
case"kw_defexpected":
returnProperties.Resources.kw_def_expected;
case"kw_externalexpected":
returnProperties.Resources.kw_external_expected;
case"kw_extendexpected":
returnProperties.Resources.kw_extend_expected;
case"kw_heapexpected":
returnProperties.Resources.kw_heap_expected;
case"kw_ifexpected":
returnProperties.Resources.kw_if_expected;
case"kw_elseifexpected":
returnProperties.Resources.kw_elseif_expected;
case"kw_elseexpected":
returnProperties.Resources.kw_else_expected;
case"kw_whileexpected":
returnProperties.Resources.kw_while_expected;
case"kw_forexpected":
returnProperties.Resources.kw_for_expected;
case"kw_importexpected":
returnProperties.Resources.kw_import_expected;
case"kw_prefixexpected":
returnProperties.Resources.kw_prefix_expected;
case"kw_fromexpected":
returnProperties.Resources.kw_from_expected;
case"kw_breakexpected":
returnProperties.Resources.kw_break_expected;
case"kw_continueexpected":
returnProperties.Resources.kw_continue_expected;
case"kw_staticexpected":
returnProperties.Resources.kw_static_expected;
case"kw_localexpected":
returnProperties.Resources.kw_local_expected;
case"literal_trueexpected":
returnProperties.Resources.literal_true_expected;
case"literal_falseexpected":
returnProperties.Resources.literal_false_expected;
case"literal_nullexpected":
returnProperties.Resources.literal_null_expected;
case"replicationguide_postfixexpected":
returnProperties.Resources.replicationguide_postfix_expected;
case"\"throw\"expected":
returnProperties.Resources.throw_expected;
case"\"{\"expected":
returnProperties.Resources.openbrace_expected;
case"\"}\"expected":
returnProperties.Resources.closebrace_expected;
case"\",\"expected":
returnProperties.Resources.comma_expected;
case"\"=\"expected":
returnProperties.Resources.equalmark_expected;
case"\":\"expected":
returnProperties.Resources.doublecolumn_expected;
case"\"public\"expected":
returnProperties.Resources.public_expected;
case"\"private\"expected":
returnProperties.Resources.private_expected;
case"\"protected\"expected":
returnProperties.Resources.protected_expected;
case"\"=>\"expected":
returnProperties.Resources.equalright_expected;
case"\"?\"expected":
returnProperties.Resources.question_expected;
case"\"try\"expected":
returnProperties.Resources.try_expected;
case"\"catch\"expected":
returnProperties.Resources.catch_expected;
case"\"+\"expected":
returnProperties.Resources.add_expected;
case"\"*\"expected":
returnProperties.Resources.asterisk_expected;
case"\"/\"expected":
returnProperties.Resources.divider_expected;
case"\"%\"expected":
returnProperties.Resources.reminder_expected;
case"\"&\"expected":
returnProperties.Resources.and_expected;
case"\"^\"expected":
returnProperties.Resources.power_expected;
case"\"&&\"expected":
returnProperties.Resources.andand_expected;
case"\"||\"expected":
returnProperties.Resources.oror_expected;
case"\"~\"expected":
returnProperties.Resources.curvedash_expected;
case"\"++\"expected":
returnProperties.Resources.addadd_expected;
case"\"--\"expected":
returnProperties.Resources.dashdash_expected;
case"\"#\"expected":
returnProperties.Resources.hax_expected;
case"\"in\"expected":
returnProperties.Resources.in_expected;
case"???expected":
returnProperties.Resources.triquestionmark_expected;
case"';'isexpected":
returnProperties.Resources.SemiColonExpected;
case"invalidHydrogen":
returnProperties.Resources.invalid_Hydrogen;
case"thissymbolnotexpectedinImport_Statement":
returnProperties.Resources.this_symbol_not_expected_in_Import_Statement;
case"invalidImport_Statement":
returnProperties.Resources.invalid_Import_Statement;
case"thissymbolnotexpectedinAssociative_Statement":
returnProperties.Resources.this_symbol_not_expected_in_Associative_Statement;
case"invalidAssociative_Statement":
returnProperties.Resources.invalid_Associative_Statement;
case"invalidAssociative_functiondecl":
returnProperties.Resources.invalid_Associative_functiondecl;
case"invalidAssociative_classdecl":
returnProperties.Resources.invalid_Associative_classdecl;
case"thissymbolnotexpectedinAssociative_NonAssignmentStatement":
returnProperties.Resources.this_symbo_no_expected_in_Associative_NonAssignmentStatement;
case"thissymbolnotexpectedinAssociative_FunctionCallStatement":
returnProperties.Resources.this_symbol_not_expected_in_Associative_FunctionCallStatement;
case"thissymbolnotexpectedinAssociative_FunctionalStatement":
returnProperties.Resources.this_symbol_not_expected_in_Associative_FunctionalStatement;
case"invalidAssociative_FunctionalStatement":
returnProperties.Resources.invalid_Associative_FunctionalStatement;
case"invalidAssociative_LanguageBlock":
returnProperties.Resources.invalid_Associative_FunctionalStatement;
case"invalidAssociative_AccessSpecifier":
returnProperties.Resources.invalid_Associative_AccessSpecifier;
case"invalidAssociative_BinaryOps":
returnProperties.Resources.invalid_Associative_BinaryOps;
case"invalidAssociative_AddOp":
returnProperties.Resources.invalid_Associative_AddOp;
case"invalidAssociative_MulOp":
returnProperties.Resources.invalid_Associative_MulOp;
case"invalidAssociative_ComparisonOp":
returnProperties.Resources.invalid_Associative_ComparisonOp;
case"invalidAssociative_LogicalOp":
returnProperties.Resources.invalid_Associative_LogicalOp;
case"invalidAssociative_DecoratedIdentifier":
returnProperties.Resources.invalid_Associative_DecoratedIdentifier;
case"invalidAssociative_UnaryExpression":
returnProperties.Resources.invalid_Associative_UnaryExpression;
case"invalidAssociative_unaryop":
returnProperties.Resources.invalid_Associative_unaryop;
case"invalidAssociative_Factor":
returnProperties.Resources.invalid_Associative_Factor;
case"invalidAssociative_negop":
returnProperties.Resources.invalid_Associative_negop;
case"invalidAssociative_BitOp":
returnProperties.Resources.invalid_Associative_BitOp;
case"invalidAssociative_PostFixOp":
returnProperties.Resources.invalid_Associative_PostFixOp;
case"invalidAssociative_Number":
returnProperties.Resources.invalid_Associative_Number;
case"invalidAssociative_Level":
returnProperties.Resources.invalid_Associative_Level;
case"invalidAssociative_NameReference":
returnProperties.Resources.invalid_Associative_NameReference;
case"invalidImperative_stmt":
returnProperties.Resources.invalid_Imperative_stmt;
case"invalidImperative_functiondecl":
returnProperties.Resources.invalid_Imperative_functiondecl;
case"invalidImperative_languageblock":
returnProperties.Resources.invalid_Imperative_languageblock;
case"invalidImperative_ifstmt":
returnProperties.Resources.invalid_Imperative_ifstmt;
case"invalidImperative_forloop":
returnProperties.Resources.invalid_Imperative_forloop;
case"invalidImperative_assignstmt":
returnProperties.Resources.invalid_Imperative_assignstmt;
case"invalidImperative_decoratedIdentifier":
returnProperties.Resources.invalid_Imperative_decoratedIdentifier;
case"invalidImperative_NameReference":
returnProperties.Resources.invalid_Imperative_NameReference;
case"invalidImperative_unaryexpr":
returnProperties.Resources.invalid_Imperative_unaryexpr;
case"invalidImperative_unaryop":
returnProperties.Resources.invalid_Imperative_unaryexpr;
case"invalidImperative_factor":
returnProperties.Resources.invalid_Imperative_factor;
case"invalidImperative_logicalop":
returnProperties.Resources.invalid_Imperative_logicalop;
case"invalidImperative_relop":
returnProperties.Resources.invalid_Imperative_relop;
case"invalidImperative_addop":
returnProperties.Resources.invalid_Imperative_addop;
case"invalidImperative_mulop":
returnProperties.Resources.invalid_Imperative_mulop;
case"invalidImperative_bitop":
returnProperties.Resources.invalid_Imperative_bitop;
case"invalidImperative_num":
returnProperties.Resources.invalid_Imperative_num;
case"invalidImperative_PostFixOp":
returnProperties.Resources.invalid_Imperative_PostFixOp;
default:
returnerrorMessage;
}
}


publicvoidLogSemanticError(stringmsg,stringfileName=null,intline=-1,intcol=-1,AssociativeGraph.GraphNodegraphNode=null)
{
#ifDEBUG
if(logErrors)
{
System.Console.WriteLine("{0}({1},{2})Error:{3}",fileName,line,col,msg);
}
#endif

if(core.Options.IsDeltaExecution)
{
}

BuildData.ErrorEntryerrorEntry=newBuildData.ErrorEntry
{
ID=ErrorType.SemanticError,
FileName=fileName,
Message=msg,
Line=line,
Column=col
};
errors.Add(errorEntry);

OutputMessageoutputmessage=newOutputMessage(OutputMessage.MessageType.Error,msg.Trim(),fileName,line,col);
if(MessageHandler!=null)
{
MessageHandler.Write(outputmessage);
if(!outputmessage.Continue)
thrownewBuildHaltException(msg);
}
thrownewBuildHaltException(msg);
}

///<summary>
///Logsthewarningwheretheusageofasymbol(symbolName)cannotbe
///resolvedbecauseitcollideswithmultiplesymbols(collidingSymbolNames)
///</summary>
///<paramname="symbolName"></param>
///<paramname="collidingSymbolNames"></param>
publicvoidLogSymbolConflictWarning(stringsymbolName,string[]collidingSymbolNames)
{
stringmessage=string.Format(Resources.kMultipleSymbolFoundFromName,symbolName,"");
message+=String.Join(",",collidingSymbolNames);
LogWarning(BuildData.WarningID.MultipleSymbolFoundFromName,message);
}

publicvoidLogDeprecatedMethodWarning(stringoldMethodName,stringnewMethodName)
{
varwarningMessage=string.Format(Resources.kMethodDeprecated,
oldMethodName,newMethodName);
LogWarning(BuildData.WarningID.FunctionNotFound,warningMessage);
}

///<summary>
///Logstheunboundvariablewarningandsetstheunboundsymbol
///</summary>
///<paramname="unboundSymbol"></param>
///<paramname="message"></param>
///<paramname="fileName"></param>
///<paramname="line"></param>
///<paramname="col"></param>
///<paramname="graphNode"></param>
publicvoidLogUnboundVariableWarning(
SymbolNodeunboundSymbol,
stringmessage,
stringfileName=null,
intline=-1,
intcol=-1,
AssociativeGraph.GraphNodegraphNode=null)
{
LogWarning(BuildData.WarningID.IdUnboundIdentifier,message,core.CurrentDSFileName,line,col,graphNode,unboundSymbol);
}

publicvoidLogWarning(BuildData.WarningIDwarningID,
stringmessage,
stringfileName=null,
intline=-1,
intcol=-1,
AssociativeGraph.GraphNodegraphNode=null,
SymbolNodeassociatedSymbol=null)
{
varentry=newBuildData.WarningEntry
{
ID=warningID,
Message=message,
Line=line,
Column=col,
GraphNodeGuid=graphNode==null?default(Guid):graphNode.guid,
AstID=graphNode==null?DSASM.Constants.kInvalidIndex:graphNode.OriginalAstID,
FileName=fileName,
UnboundVariableSymbolNode=associatedSymbol
};
warnings.Add(entry);

if(LogWarnings)
{
#ifDEBUG

System.Console.WriteLine("{0}({1},{2})Warning:{3}",fileName,line,col,message);
#endif

OutputMessageoutputmessage=newOutputMessage(OutputMessage.MessageType.Warning,message.Trim(),fileName,line,col);
if(MessageHandler!=null)
{
MessageHandler.Write(outputmessage);
if(!outputmessage.Continue)
thrownewBuildHaltException(message);
}
}
}

publicvoidReportBuildResult()
{
stringbuildResult=string.Format("==========Build:{0}error(s),{1}warning(s)==========\n",errors.Count,warnings.Count);

if(displayBuildResult)
{
#ifDEBUG
System.Console.WriteLine(buildResult);
#endif

if(MessageHandler!=null)
{
varoutputMsg=newOutputMessage(buildResult);
MessageHandler.Write(outputMsg);
}
}
}
	}
}

